apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
spec:
  replicas: {{ .Values.Deployments.app_replicas }}
  selector:
    matchLabels:
      app: {{ .Values.Deployments.app_namenodejs }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: {{ .Values.Deployments.app_namenodejs }}
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: nodejs
        image: {{ .Values.Deployments.app_urlnodejs }}
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: TITLE
          value: "Welcome AKS Ingress chatapp"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Service.app_namenodejs }}
  labels:
    run: {{ .Values.Service.app_namenodejs }}
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: {{ .Values.Service.app_namenodejs }}
#  type: LoadBalancer  
